vim.g.mapleader = ' '
vim.g.maplocalleader = ' '
vim.bo.filetype = 'on'
vim.o.syntax = 'enable'
vim.o.termguicolors = true
vim.o.hidden = true
vim.o.tabstop = 4
vim.o.softtabstop = 4
vim.o.shiftwidth = 4
vim.o.expandtab = true
vim.o.scrolloff = 8
vim.o.ignorecase = true
vim.o.smartcase = true
vim.o.laststatus = 3
vim.o.number = true
vim.o.relativenumber = true
vim.o.cursorline = true

vim.opt.mouse = ""
